title: CV Version Imprimable
ignore:
  - styles
  - print.css
  - print.js

layout: cv

bypass:
  styles: true

styles:
  - styles/cv.css
  - print.css

scripts:
  - print.js

external links arrow: false