site:
  name: Nicolas Peugnet
  description: A quick description of the website

page defaults:
  sort:
    type: alpha
    order: asc
  render: title
  layout: page

date formats:
  - d/m/Y H:i:s
  - d/m/Y H:i
  - d/m/Y

# you don't really need to edit these settings
system:
  public dir: public