ignore:
  - 403
  - 404
  - a-propos
  - contact
  - README.md
  - live-youtube

sort:
  - type: alpha
    order: desc
  - type: date
    order: desc
  custom:

render:
  - title
  - cover

custom:
  render:
    test: cover
  sort:
    - *
    - 2014

title: Nicolas Peugnet