ignore:
  - 403/
  - 404/
  - assets/
  - a-propos/
  - contact/
  - README.md

sort:
  - type: alpha
    order: desc
  - type: lastModif
    order: desc
  custom:

render:
  - list
  - covers

title: Nicolas Peugnet