ignore:
  - 403
  - 404
  - assets
  - a-propos
  - contact
  - README.md

sort:
  - type: alpha
    order: desc
  - type: date
    order: desc

render:
  - list
  - cover

custom:
  render:
    test: cover
  sort:
    - *
    - 2014

title: Nicolas Peugnet