ignore:
  - 403/
  - 404/
  - assets/
  - a-propos/
  - contact/
  - README.md

sort:
  order: desc
  type: alpha
  recursive: false
  # childrens:
  #   order: desc
  #   type: lastModif
  #   recursive: false
  custom:

render:
  - list
  - covers

title: Nicolas Peugnet